version: "3"

services:

  app:
    container_name: export-xls
    build:
      context: .
      dockerfile: Dockerfile    
    volumes:
      - ./www/:/var/www/
    expose:
      - 80
    ports:
      - 80:80
    links: 
      - database
    networks:
      kumbiaphp_net:
        ipv4_address: 172.60.10.2

  database:
    container_name: mysql-kumbiaphp
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_DATABASE=export_xls
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=kumbiaphp
      - MYSQL_PASSWORD=password
    volumes:
      - ./data/mysql:/var/lib/mysql
    expose:
      - 3306
    ports:
      - 3306:3306
    networks:
      kumbiaphp_net:
       ipv4_address: 172.60.10.3
networks:
  kumbiaphp_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.60.0.0/16